#!/usr/bin/env node

var fs = require('fs');
var jade = require('jade');

var catalog = require('./catalog.json');
catalog.forEach(function(post) {
  post.html = fs.readFileSync(post.path, 'utf8');
})

var html = jade.renderFile('./templates/home.jade', {
  'title': 'Under Tech.',
  'posts': catalog
});
fs.writeFileSync('index.html', html);